# Generated by Django 4.2.4 on 2023-09-09 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_box', models.CharField(choices=[('coffret 3500', 'coffret 3500'), ('coffret 4000', 'coffret 4000'), ('coffret 4500', 'coffret 4500'), ('coffret 7500', 'coffret 7500'), ('coffret 8500', 'coffret 8500'), ('coffret 9900', 'coffret 9900')], max_length=50, unique=True)),
                ('quantity_in_stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FilledBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_date', models.DateField(auto_now_add=True)),
                ('quantity_fill_box', models.PositiveIntegerField(default=0)),
                ('jars_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('box_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAssilStockManag.box')),
            ],
        ),
        migrations.CreateModel(
            name='FilledJar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_field', models.PositiveBigIntegerField()),
                ('filled_date', models.DateField(auto_now_add=True)),
                ('size', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='HoneyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=255, unique=True)),
                ('quantity_in_the_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_entry', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField(choices=[(0.01, '10g'), (0.1, '100g'), (0.125, '125g'), (0.2, '200g'), (0.25, '250g'), (0.5, '500g')], unique=True)),
                ('quantity_in_the_stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ticket', models.CharField(choices=[('10g', '10g'), ('100g', '100g'), ('125g', '125g'), ('200g', '200g'), ('250g', '250g'), ('500g', '500g')], max_length=50)),
                ('quantity_in_the_stock', models.IntegerField(default=0)),
                ('date_entry', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAssilStockManag.honeyproduct')),
            ],
        ),
        migrations.CreateModel(
            name='TicketBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_entry', models.DateField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAssilStockManag.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='SoldFilledJar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_date', models.DateField(auto_now_add=True)),
                ('quantity_sell_jars', models.IntegerField(default=1)),
                ('price_sell', models.DecimalField(decimal_places=2, max_digits=10)),
                ('filled_jar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAssilStockManag.filledjar')),
            ],
        ),
        migrations.CreateModel(
            name='SoldFilledBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_date', models.DateField(auto_now_add=True)),
                ('quantity_sell_box', models.IntegerField(default=1)),
                ('price_sell', models.DecimalField(decimal_places=2, max_digits=10)),
                ('filled_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAssilStockManag.filledbox')),
            ],
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField(auto_now_add=True)),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAssilStockManag.honeyproduct')),
            ],
        ),
        migrations.CreateModel(
            name='JarBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField(auto_now_add=True)),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_jar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAssilStockManag.jar')),
            ],
        ),
        migrations.AddField(
            model_name='filledjar',
            name='jar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAssilStockManag.jar'),
        ),
        migrations.AddField(
            model_name='filledjar',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAssilStockManag.honeyproduct'),
        ),
        migrations.AddField(
            model_name='filledjar',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAssilStockManag.sku'),
        ),
        migrations.CreateModel(
            name='FilledBoxJars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAssilStockManag.filledbox')),
                ('jar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAssilStockManag.filledjar')),
            ],
        ),
        migrations.AddField(
            model_name='filledbox',
            name='filled_jars',
            field=models.ManyToManyField(through='appAssilStockManag.FilledBoxJars', to='appAssilStockManag.filledjar'),
        ),
        migrations.AddField(
            model_name='filledbox',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAssilStockManag.sku'),
        ),
        migrations.CreateModel(
            name='BoxBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('date_entry', models.DateField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAssilStockManag.box')),
            ],
        ),
    ]
