# Generated by Django 4.2.4 on 2023-09-14 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAssilStockManag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filledjar',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAssilStockManag.sku'),
        ),
    ]
