# Generated by Django 4.2.4 on 2023-09-01 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAssilStockManag', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filledbox',
            old_name='quantity',
            new_name='quantity_fill_box',
        ),
    ]
