# Generated by Django 4.2.4 on 2023-09-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAssilStockManag', '0002_alter_honeyproduct_name_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jar',
            name='size',
            field=models.FloatField(choices=[(0.01, '10g'), (0.1, '100g'), (0.125, '125g'), (0.2, '200g'), (0.25, '250g'), (0.5, '500g')], unique=True),
        ),
    ]
