# Generated by Django 4.2.4 on 2023-09-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAssilStockManag', '0003_boxstandard'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
