# Generated by Django 4.2.4 on 2023-09-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAssilStockManag', '0003_alter_jar_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type_ticket',
            field=models.CharField(choices=[('10g', '10g'), ('100g', '100g'), ('125g', '125g'), ('200g', '200g'), ('250g', '250g'), ('500g', '500g')], max_length=50, unique=True),
        ),
    ]
