# Generated by Django 4.2.4 on 2023-09-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAssilStockManag', '0004_alter_ticket_type_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='type_box',
            field=models.CharField(choices=[('coffret 3500', 'coffret 3500'), ('coffret 4000', 'coffret 4000'), ('coffret 4500', 'coffret 4500'), ('coffret 7500', 'coffret 7500'), ('coffret 8500', 'coffret 8500'), ('coffret 9900', 'coffret 9900')], max_length=50, unique=True),
        ),
    ]
