# Generated by Django 4.2.4 on 2023-09-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appAssilStockManag', '0006_rename_quantity_sell_jars_soldfilledbox_quantity_sell_box_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type_ticket',
            field=models.CharField(choices=[('10g', '10g'), ('100g', '100g'), ('125g', '125g'), ('200g', '200g'), ('250g', '250g'), ('500g', '500g')], max_length=50),
        ),
    ]
