# Generated by Django 4.2.4 on 2023-09-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAssilStockManag', '0007_alter_ticket_type_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filledbox',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appAssilStockManag.sku'),
        ),
    ]
