# Generated by Django 4.2.4 on 2023-09-17 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appAssilStockManag', '0002_alter_filledjar_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_number', models.PositiveBigIntegerField()),
                ('filled_jars', models.ManyToManyField(to='appAssilStockManag.filledjar')),
                ('type_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appAssilStockManag.box')),
            ],
        ),
    ]
