# Generated by Django 4.2.4 on 2023-09-23 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAssilStockManag', '0004_sku_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='quantity',
        ),
    ]
